export const ADD_WARNINGS = 'ADD_WARNINGS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS'

export const ADD_GROUPS = 'ADD_GROUPS'
export const ADD_GROUP = 'ADD_GROUP'

export const SHOW_SPECIFIC_CHAT = 'SHOW_SPECIFIC_CHAT'
export const SHOW_SPECIFIC_CHAT_ERROR = 'SHOW_SPECIFIC_CHAT_ERROR'

export const CREATEGROUP_FAILURE = 'CREATEGROUP_FAILURE'
export const EDITGROUP_RESPONSE = 'EDITGROUP_RESPONSE'
export const ADD_SELECTED_GROUP = 'ADD_SELECTED_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const DELETE_AGENT = 'DELETE_AGENT'
export const ADD_AGENTS = 'ADD_AGENTS'
export const ADD_DEPTAGENTS = 'ADD_DEPTAGENTS'
