export const ADD_WARNINGS = 'ADD_WARNINGS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const ADD_USER_DETAILS = 'ADD_USER_DETAILS'

export const ADD_GROUPS = 'ADD_GROUPS'
export const ADD_GROUP = 'ADD_GROUP'
